services:
  cooking-nonna:
    build: service
    restart: unless-stopped
    ports:
      - '2222:2222'
    command: 'socaz --timeout 10000 --debug --uid 65534 --gid 65534 --bind 2222 --cmd /chall/main'
    volumes:
      - './service/build:/chall:ro'
      - './data:/data'

  cleaner:
    build: cleaner
    restart: unless-stopped
    volumes:
      - "./data:/tmp/data"
    depends_on:
      - cooking-nonna
